"""add task tag relationship

Revision ID: 03eb3e46bddd
Revises: eaaa3c8e7b0f
Create Date: 2026-06-20 06:18:25.001548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03eb3e46bddd'
down_revision: Union[str, Sequence[str], None] = 'eaaa3c8e7b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
