// Suggested tasks generated by AI assistant for immediate momentum.
function SuggestedTasks() {
  const tasks = [
    "Finish Dashboard UI",
    "Review overdue tasks",
    "Complete frontend responsiveness",
  ];

  return (
    <section className="space-y-2">
      <p className="text-xs uppercase tracking-wide text-gray-400">Suggested Tasks</p>
      <ul className="space-y-2">
        {tasks.map((task) => (
          <li key={task} className="rounded-xl bg-gray-50 px-3 py-2 text-sm text-gray-700">
            {task}
          </li>
        ))}
      </ul>
    </section>
  );
}

export default SuggestedTasks;
